name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-latest

    strategy:
      matrix: { ruby: ['2.7', '3.0', '3.1', '3.2', head] }

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up bundle cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-bundle

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '${{ matrix.ruby }}'
        bundler-cache: true

    - name: Install stress
      run: sudo apt install -y stress

    - name: Run tests
      run: bundle exec rspec
